% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Data Cleaning Process},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Data Cleaning Process}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\hypertarget{data-context}{%
\subsection{Data context}\label{data-context}}

\begin{itemize}
\tightlist
\item
  Case company: an online retailer based in the UK. The business is
  fully e-commerce business without any physical store.
\item
  Products: all-occasions gifts
\item
  Customers: mainly wholesalers
\item
  Data period: \textbf{1st of Dec, 2010 - 9nd of Dec, 2011}
\end{itemize}

\hypertarget{data-import}{%
\subsection{Data import}\label{data-import}}

The first step of data cleaning tasks is to import the data. `readr'
package was used for the ease of importing data and changing the data
type of `Invoice' column to character, `Quantity' column to integer, and
`InvoiceDate' column to date-time.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Import CSV file using 'readr' package}

\KeywordTok{library}\NormalTok{(readr)}
\NormalTok{online_retail_II <-}\StringTok{ }\KeywordTok{read_csv}\NormalTok{(}\StringTok{"C:/Users/Tan/Desktop/kitty/R/R Projects/E-commerce Data/online_retail_II.csv"}\NormalTok{, }
                             \DataTypeTok{col_types =} \KeywordTok{cols}\NormalTok{(}\DataTypeTok{Invoice =} \KeywordTok{col_character}\NormalTok{(), }
                                              \DataTypeTok{Quantity =} \KeywordTok{col_integer}\NormalTok{(), }\DataTypeTok{InvoiceDate =} \KeywordTok{col_datetime}\NormalTok{(}\DataTypeTok{format =} \StringTok{"%d/%m/%Y %H.%M"}\NormalTok{)))}
\KeywordTok{head}\NormalTok{(online_retail_II)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 8
##   Invoice StockCode Description Quantity InvoiceDate         Price `Customer ID`
##   <chr>   <chr>     <chr>          <int> <dttm>              <dbl>         <dbl>
## 1 536365  85123A    WHITE HANG~        6 2010-12-01 08:26:00  2.55         17850
## 2 536365  71053     WHITE META~        6 2010-12-01 08:26:00  3.39         17850
## 3 536365  84406B    CREAM CUPI~        8 2010-12-01 08:26:00  2.75         17850
## 4 536365  84029G    KNITTED UN~        6 2010-12-01 08:26:00  3.39         17850
## 5 536365  84029E    RED WOOLLY~        6 2010-12-01 08:26:00  3.39         17850
## 6 536365  22752     SET 7 BABU~        2 2010-12-01 08:26:00  7.65         17850
## # ... with 1 more variable: Country <chr>
\end{verbatim}

\hypertarget{change-the-name-of-customer-id-column-and-data-summary}{%
\subsection{Change the name of `Customer ID' column and Data
summary}\label{change-the-name-of-customer-id-column-and-data-summary}}

Using \emph{summary()} function to have an overview at the dataset

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{online_retail_II<-}\StringTok{ }\KeywordTok{rename}\NormalTok{(online_retail_II, }\StringTok{"CustomerID"}\NormalTok{ =}\StringTok{ "Customer ID"}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(online_retail_II)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Invoice           StockCode         Description           Quantity        
##  Length:541910      Length:541910      Length:541910      Min.   :-80995.00  
##  Class :character   Class :character   Class :character   1st Qu.:     1.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :     3.00  
##                                                           Mean   :     9.55  
##                                                           3rd Qu.:    10.00  
##                                                           Max.   : 80995.00  
##                                                                              
##   InvoiceDate                      Price             CustomerID    
##  Min.   :2010-12-01 08:26:00   Min.   :-11062.06   Min.   :12346   
##  1st Qu.:2011-03-28 11:34:00   1st Qu.:     1.25   1st Qu.:13953   
##  Median :2011-07-19 17:17:00   Median :     2.08   Median :15152   
##  Mean   :2011-07-04 13:35:22   Mean   :     4.61   Mean   :15288   
##  3rd Qu.:2011-10-19 11:27:00   3rd Qu.:     4.13   3rd Qu.:16791   
##  Max.   :2011-12-09 12:50:00   Max.   : 38970.00   Max.   :18287   
##                                                    NA's   :135080  
##    Country         
##  Length:541910     
##  Class :character  
##  Mode  :character  
##                    
##                    
##                    
## 
\end{verbatim}

Notice that there are \textbf{negative values} in `Quantity' column,
which is invalid. There are also \textbf{missing values} in
`CustomerID'.

\hypertarget{deal-with-missing-values-and-quantity-negative-values}{%
\subsection{Deal with missing values and `Quantity' negative
values}\label{deal-with-missing-values-and-quantity-negative-values}}

\textbf{Strategy to deal with negative values and missing values}:
Deleting the rows with negative values and missing values.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Remove rows with negative quantity}
\NormalTok{online_retail_II <-}\StringTok{ }\NormalTok{online_retail_II[online_retail_II}\OperatorTok{$}\NormalTok{Quantity }\OperatorTok{>}\StringTok{ }\DecValTok{0}\NormalTok{,]}
\CommentTok{#Remove rows with missing values}
\NormalTok{online_retail_II <-}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(online_retail_II)}
\CommentTok{#Review the dataset}
\KeywordTok{summary}\NormalTok{(online_retail_II)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Invoice           StockCode         Description           Quantity       
##  Length:397925      Length:397925      Length:397925      Min.   :    1.00  
##  Class :character   Class :character   Class :character   1st Qu.:    2.00  
##  Mode  :character   Mode  :character   Mode  :character   Median :    6.00  
##                                                           Mean   :   13.02  
##                                                           3rd Qu.:   12.00  
##                                                           Max.   :80995.00  
##   InvoiceDate                      Price            CustomerID   
##  Min.   :2010-12-01 08:26:00   Min.   :   0.000   Min.   :12346  
##  1st Qu.:2011-04-07 11:12:00   1st Qu.:   1.250   1st Qu.:13969  
##  Median :2011-07-31 14:39:00   Median :   1.950   Median :15159  
##  Mean   :2011-07-10 23:44:09   Mean   :   3.116   Mean   :15294  
##  3rd Qu.:2011-10-20 14:33:00   3rd Qu.:   3.750   3rd Qu.:16795  
##  Max.   :2011-12-09 12:50:00   Max.   :8142.750   Max.   :18287  
##    Country         
##  Length:397925     
##  Class :character  
##  Mode  :character  
##                    
##                    
## 
\end{verbatim}

\hypertarget{redefine-data-types-of-variables}{%
\subsection{Redefine data types of
variables}\label{redefine-data-types-of-variables}}

Change data type of `Country', `CustomerID', `Invoice', `StockCode',
`Description' variables to \textbf{Factor} using \emph{as.factor()}
function

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Country <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Country)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{CustomerID <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{CustomerID)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Invoice <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Invoice)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{StockCode <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{StockCode)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Description <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Description)}
\end{Highlighting}
\end{Shaded}

\hypertarget{add-customize-variables-to-the-dataset}{%
\subsection{Add customize variables to the
dataset}\label{add-customize-variables-to-the-dataset}}

\begin{itemize}
\tightlist
\item
  Add `Amount\_Spent' column by multiply `Quantity' with `Price'
\item
  Add `Day\_of\_the\_week', `Month\_YR', `Hour' columns and change their
  data types to \textbf{Factor}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Add 'Amount_Spent' column}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Amount_spent <-}\StringTok{ }\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Quantity }\OperatorTok{*}\StringTok{ }\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Price}
\CommentTok{#Add Day_of_the_week, Month_YR, Hour columns and change them to factor data type}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Day_of_the_week <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{weekdays}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{InvoiceDate)) }\CommentTok{#there is no order on Saturday}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Month_Yr <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{format}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{InvoiceDate, }\StringTok{"%Y-%m"}\NormalTok{))}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Hour <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(}\KeywordTok{format}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{InvoiceDate, }\StringTok{"%H"}\NormalTok{))}
\KeywordTok{summary}\NormalTok{(online_retail_II)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Invoice         StockCode                                  Description    
##  576339 :   542   85123A :  2035   WHITE HANGING HEART T-LIGHT HOLDER:  2028  
##  579196 :   533   22423  :  1724   REGENCY CAKESTAND 3 TIER          :  1724  
##  580727 :   529   85099B :  1618   JUMBO BAG RED RETROSPOT           :  1618  
##  578270 :   442   84879  :  1408   ASSORTED COLOUR BIRD ORNAMENT     :  1408  
##  573576 :   435   47566  :  1397   PARTY BUNTING                     :  1397  
##  567656 :   421   20725  :  1317   LUNCH BAG RED RETROSPOT           :  1316  
##  (Other):395023   (Other):388426   (Other)                           :388434  
##     Quantity         InvoiceDate                      Price         
##  Min.   :    1.00   Min.   :2010-12-01 08:26:00   Min.   :   0.000  
##  1st Qu.:    2.00   1st Qu.:2011-04-07 11:12:00   1st Qu.:   1.250  
##  Median :    6.00   Median :2011-07-31 14:39:00   Median :   1.950  
##  Mean   :   13.02   Mean   :2011-07-10 23:44:09   Mean   :   3.116  
##  3rd Qu.:   12.00   3rd Qu.:2011-10-20 14:33:00   3rd Qu.:   3.750  
##  Max.   :80995.00   Max.   :2011-12-09 12:50:00   Max.   :8142.750  
##                                                                     
##    CustomerID               Country        Amount_spent        Day_of_the_week 
##  17841  :  7847   United Kingdom:354345   Min.   :     0.00   Friday   :54835  
##  14911  :  5677   Germany       :  9042   1st Qu.:     4.68   Monday   :64899  
##  14096  :  5111   France        :  8343   Median :    11.80   Sunday   :62775  
##  12748  :  4596   EIRE          :  7238   Mean   :    22.39   Thursday :80052  
##  14606  :  2700   Spain         :  2485   3rd Qu.:    19.80   Tuesday  :66476  
##  15311  :  2379   Netherlands   :  2363   Max.   :168469.60   Wednesday:68888  
##  (Other):369615   (Other)       : 14109                                        
##     Month_Yr           Hour      
##  2011-11: 64545   12     :72070  
##  2011-10: 49557   13     :64031  
##  2011-09: 40030   14     :54127  
##  2011-05: 28322   11     :49092  
##  2011-06: 27185   15     :45372  
##  2011-03: 27177   10     :37999  
##  (Other):161109   (Other):75234
\end{verbatim}

\hypertarget{redefine-data-types-of-variables-1}{%
\subsection{Redefine data types of
variables}\label{redefine-data-types-of-variables-1}}

Change data type of `Country', `CustomerID', `Invoice', `StockCode',
`Description' variables to \textbf{Factor} using \emph{as.factor()}
function

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Country <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Country)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{CustomerID <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{CustomerID)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Invoice <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Invoice)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{StockCode <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{StockCode)}
\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Description <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(online_retail_II}\OperatorTok{$}\NormalTok{Description)}
\end{Highlighting}
\end{Shaded}

\hypertarget{managing-duplicate-data}{%
\subsection{Managing duplicate data}\label{managing-duplicate-data}}

The main goal of this step is to detect possible identical data and
consider if they are duplicate or just normal identical data by chance.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{online_retail_II[}\KeywordTok{duplicated}\NormalTok{(online_retail_II),]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5,192 x 12
##    Invoice StockCode Description Quantity InvoiceDate         Price CustomerID
##    <fct>   <fct>     <fct>          <int> <dttm>              <dbl> <fct>     
##  1 536409  21866     UNION JACK~        1 2010-12-01 11:45:00  1.25 17908     
##  2 536409  22866     HAND WARME~        1 2010-12-01 11:45:00  2.1  17908     
##  3 536409  22900     SET 2 TEA ~        1 2010-12-01 11:45:00  2.95 17908     
##  4 536409  22111     SCOTTIE DO~        1 2010-12-01 11:45:00  4.95 17908     
##  5 536412  22327     ROUND SNAC~        1 2010-12-01 11:49:00  2.95 17920     
##  6 536412  22273     FELTCRAFT ~        1 2010-12-01 11:49:00  2.95 17920     
##  7 536412  22749     FELTCRAFT ~        1 2010-12-01 11:49:00  3.75 17920     
##  8 536412  22141     CHRISTMAS ~        1 2010-12-01 11:49:00  2.1  17920     
##  9 536412  21448     12 DAISY P~        1 2010-12-01 11:49:00  1.65 17920     
## 10 536412  22569     FELTCRAFT ~        2 2010-12-01 11:49:00  3.75 17920     
## # ... with 5,182 more rows, and 5 more variables: Country <fct>,
## #   Amount_spent <dbl>, Day_of_the_week <fct>, Month_Yr <fct>, Hour <fct>
\end{verbatim}

It seems like there are 5,192 rows of duplicate data, however,
considering the character of e-commerce dataset, it's possible and
normal to have customer add the same product to the cart at the same
time. Therefore, the identical data wasn't deleted out of the dataset.

\hypertarget{managing-outliers-in-the-data}{%
\subsection{Managing outliers in the
data}\label{managing-outliers-in-the-data}}

The goal of this step is to detect of outliers in the numeric or integer
variables and consider if the outliers are relevant to the dataset or
just typos. This report uses the \textbf{Six Sigma Method} for outliers
detection.

\textbf{`Price' variable} outliers detection:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x =}\StringTok{ }\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Price}
\NormalTok{t =}\StringTok{ }\DecValTok{3}
\NormalTok{m =}\StringTok{ }\KeywordTok{mean}\NormalTok{(x, }\DataTypeTok{na.rm =}\NormalTok{ F)}
\NormalTok{s =}\StringTok{ }\KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm =}\NormalTok{ F)}
\NormalTok{b1 =}\StringTok{ }\NormalTok{m}\OperatorTok{-}\NormalTok{s}\OperatorTok{*}\NormalTok{t}
\NormalTok{b2 =}\StringTok{ }\NormalTok{m}\OperatorTok{+}\NormalTok{s}\OperatorTok{*}\NormalTok{t}
\NormalTok{y =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(x}\OperatorTok{>=}\StringTok{ }\NormalTok{b1 }\OperatorTok{&}\StringTok{ }\NormalTok{x}\OperatorTok{<=}\StringTok{ }\NormalTok{b2, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\CommentTok{#Plot for outliers detection of 'Price' variable}
\KeywordTok{plot}\NormalTok{(x, }\DataTypeTok{col=}\NormalTok{ y}\OperatorTok{+}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Data-Cleaning-Process_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Possible outliers}
\NormalTok{outl =}\StringTok{ }\KeywordTok{which}\NormalTok{(y}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\NormalTok{online_retail_II[outl,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 221 x 12
##    Invoice StockCode Description Quantity InvoiceDate         Price CustomerID
##    <fct>   <fct>     <fct>          <int> <dttm>              <dbl> <fct>     
##  1 536392  22827     RUSTIC  SE~        1 2010-12-01 10:29:00 165   13705     
##  2 536676  21769     VINTAGE PO~        1 2010-12-02 12:18:00  80.0 16752     
##  3 536835  22655     VINTAGE RE~        1 2010-12-02 18:06:00 295   13145     
##  4 537859  22828     REGENCY MI~        1 2010-12-08 16:11:00 165   14030     
##  5 537859  22827     RUSTIC  SE~        2 2010-12-08 16:11:00 145   14030     
##  6 538354  22826     LOVE SEAT ~        2 2010-12-10 15:45:00 175   16873     
##  7 538662  22655     VINTAGE RE~        2 2010-12-13 15:44:00 125   15159     
##  8 538662  22656     VINTAGE BL~        2 2010-12-13 15:44:00 125   15159     
##  9 538999  22655     VINTAGE RE~        2 2010-12-15 12:09:00 125   16003     
## 10 538999  22656     VINTAGE BL~        2 2010-12-15 12:09:00 125   16003     
## # ... with 211 more rows, and 5 more variables: Country <fct>,
## #   Amount_spent <dbl>, Day_of_the_week <fct>, Month_Yr <fct>, Hour <fct>
\end{verbatim}

\textbf{`Quantity' variable} outliers detection:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xs =}\StringTok{ }\NormalTok{online_retail_II}\OperatorTok{$}\NormalTok{Quantity}
\NormalTok{ts =}\StringTok{ }\DecValTok{3}
\NormalTok{ms =}\StringTok{ }\KeywordTok{mean}\NormalTok{(x,}\DataTypeTok{na.rm =}\NormalTok{ F)}
\NormalTok{ss =}\StringTok{ }\KeywordTok{sd}\NormalTok{(x, }\DataTypeTok{na.rm =}\NormalTok{ F)}
\NormalTok{b1s =}\StringTok{ }\NormalTok{ms }\OperatorTok{-}\StringTok{ }\NormalTok{ss}\OperatorTok{*}\NormalTok{ts}
\NormalTok{b2s =}\StringTok{ }\NormalTok{ms }\OperatorTok{+}\StringTok{ }\NormalTok{ss}\OperatorTok{*}\NormalTok{ts}
\NormalTok{ys =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(xs}\OperatorTok{>=}\StringTok{ }\NormalTok{b1s }\OperatorTok{&}\StringTok{ }\NormalTok{xs}\OperatorTok{<=}\StringTok{ }\NormalTok{b2s, }\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{)}
\CommentTok{#Plot for outliers detection of 'Quantity' variable}
\KeywordTok{plot}\NormalTok{(xs,}\DataTypeTok{col=}\NormalTok{ ys}\OperatorTok{+}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Data-Cleaning-Process_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Possible outliers}
\NormalTok{outls =}\StringTok{ }\KeywordTok{which}\NormalTok{(ys}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\NormalTok{online_retail_II[outls,]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10,594 x 12
##    Invoice StockCode Description Quantity InvoiceDate         Price CustomerID
##    <fct>   <fct>     <fct>          <int> <dttm>              <dbl> <fct>     
##  1 536371  22086     PAPER CHAI~       80 2010-12-01 09:00:00  2.55 13748     
##  2 536378  21212     PACK OF 72~      120 2010-12-01 09:37:00  0.42 14688     
##  3 536378  85071B    RED CHARLI~       96 2010-12-01 09:37:00  0.38 14688     
##  4 536386  85099C    JUMBO  BAG~      100 2010-12-01 09:57:00  1.65 16029     
##  5 536386  85099B    JUMBO BAG ~      100 2010-12-01 09:57:00  1.65 16029     
##  6 536387  79321     CHILLI LIG~      192 2010-12-01 09:58:00  3.82 16029     
##  7 536387  22780     LIGHT GARL~      192 2010-12-01 09:58:00  3.37 16029     
##  8 536387  22779     WOODEN OWL~      192 2010-12-01 09:58:00  3.37 16029     
##  9 536387  22466     FAIRY TALE~      432 2010-12-01 09:58:00  1.45 16029     
## 10 536387  21731     RED TOADST~      432 2010-12-01 09:58:00  1.25 16029     
## # ... with 10,584 more rows, and 5 more variables: Country <fct>,
## #   Amount_spent <dbl>, Day_of_the_week <fct>, Month_Yr <fct>, Hour <fct>
\end{verbatim}

There are 221 possible outliers for `Price' variable and 10,594 possible
outliers for `Quantity' in the dataset. However, considering the
characters of the e-commerce dataset, it's possible that there were
customers ordered a huge quantity of products and there were also
possible expensive products. Therefore, this report didn't exclude the
possible outliers

\hypertarget{plausibility-check-for-factor-and-date-time-variables}{%
\subsection{Plausibility check for Factor and Date-time
variables}\label{plausibility-check-for-factor-and-date-time-variables}}

This step is to detect any invalid values of Factor and Date-time
variables using \emph{summary()} function.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(online_retail_II)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Invoice         StockCode                                  Description    
##  576339 :   542   85123A :  2035   WHITE HANGING HEART T-LIGHT HOLDER:  2028  
##  579196 :   533   22423  :  1724   REGENCY CAKESTAND 3 TIER          :  1724  
##  580727 :   529   85099B :  1618   JUMBO BAG RED RETROSPOT           :  1618  
##  578270 :   442   84879  :  1408   ASSORTED COLOUR BIRD ORNAMENT     :  1408  
##  573576 :   435   47566  :  1397   PARTY BUNTING                     :  1397  
##  567656 :   421   20725  :  1317   LUNCH BAG RED RETROSPOT           :  1316  
##  (Other):395023   (Other):388426   (Other)                           :388434  
##     Quantity         InvoiceDate                      Price         
##  Min.   :    1.00   Min.   :2010-12-01 08:26:00   Min.   :   0.000  
##  1st Qu.:    2.00   1st Qu.:2011-04-07 11:12:00   1st Qu.:   1.250  
##  Median :    6.00   Median :2011-07-31 14:39:00   Median :   1.950  
##  Mean   :   13.02   Mean   :2011-07-10 23:44:09   Mean   :   3.116  
##  3rd Qu.:   12.00   3rd Qu.:2011-10-20 14:33:00   3rd Qu.:   3.750  
##  Max.   :80995.00   Max.   :2011-12-09 12:50:00   Max.   :8142.750  
##                                                                     
##    CustomerID               Country        Amount_spent        Day_of_the_week 
##  17841  :  7847   United Kingdom:354345   Min.   :     0.00   Friday   :54835  
##  14911  :  5677   Germany       :  9042   1st Qu.:     4.68   Monday   :64899  
##  14096  :  5111   France        :  8343   Median :    11.80   Sunday   :62775  
##  12748  :  4596   EIRE          :  7238   Mean   :    22.39   Thursday :80052  
##  14606  :  2700   Spain         :  2485   3rd Qu.:    19.80   Tuesday  :66476  
##  15311  :  2379   Netherlands   :  2363   Max.   :168469.60   Wednesday:68888  
##  (Other):369615   (Other)       : 14109                                        
##     Month_Yr           Hour      
##  2011-11: 64545   12     :72070  
##  2011-10: 49557   13     :64031  
##  2011-09: 40030   14     :54127  
##  2011-05: 28322   11     :49092  
##  2011-06: 27185   15     :45372  
##  2011-03: 27177   10     :37999  
##  (Other):161109   (Other):75234
\end{verbatim}

There is no invalid factor or date-time values detected from the
dataset.

\end{document}
